spring.application.name=EcommerceProject

project.image=images/

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update

jwt.token.expiration-time = 3000000000
jwt.signature = SGVsbG8gTmFhIGRoYW4gTXVrZXNoICwgTmFhIGlwcG8gc3ByaW5nIHNlY3VyaXR5IGxlYXJuIHBhbm5pdHUgaXJ1a2tlbiAsIHNvIGVubm9kYSBqd3QgY29kZSBvciBzZWNyZXQga2V5IGlkaHUgZGhhbiBkYSAh